CREATE TABLE ArticleCategories
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name VARCHAR(20) NOT NULL
);

CREATE TABLE Articles
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Title VARCHAR(40) NOT NULL,
	Content VARCHAR(max) NOT NULL,
	Thumbnail VARCHAR(255) NOT NULL,
	IdCategory INT,
	CreationTime DATETIME NOT NULL DEFAULT GETUTCDATE(),
	CONSTRAINT fbk1_Articles FOREIGN KEY (IdCategory) REFERENCES ArticleCategories(Id)
);	