CREATE TABLE ContactRequests
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(40) NOT NULL,
	LastName VARCHAR(40) NOT NULL,
	Email VARCHAR(80) NOT NULL,
	Phone CHAR(14),
	Subject VARCHAR(40) NOT NULL,
	Description VARCHAR(max) NOT NULL,
	SendTime DATETIME NOT NULL DEFAULT GETUTCDATE()
);